apiVersion: v1
kind: Service
metadata:
  name: "{{ default "marxdown" .Values.serviceName }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ default "marxdown" .Values.deploymentName }}"
    subsystem: "{{ .Values.subsystem }}"
    container: "{{ .Values.siteName }}"
    service-group: ui
    log-style: uwsgi
    env: "{{ .Values.namespace }}"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: "{{ default "marxdown" .Values.deploymentName }}"
